version: '20'

services:
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.DockerFile
        volumes:
            - ./:/app
        links:
            - mysql
        working_dir: /app
        user: '1000:1000'
        ports:
            - 8000:8000
        command: php -S 0.0.0.0:8000 -t /app/public/
    mysql:
        image: mysql:8.0
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ws-tools